-- MEDICAMENTOS

DELETE FROM SC_MEDICAMENTO;
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (1, 'diclofenaco',          'Diclac P','SANDOZ','SUSPENSAO ORAL 1,8 MG/ML');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (2, 'diclofenaco potassico','Clofen K','NECKERMAN','COMP. REV. 50MG');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (3, 'diclofenaco potassico','Diclac P','SANDOZ','DRAGEA SIMPLES 50MG');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (4, 'diclofenaco potassico','Fenaflan','TEUTO','COMP. DISPERSIVEL 44,3MG');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (5, 'diclofenaco potassico','Fenaflan','TEUTO','COMP. REV. 50MG');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (6, 'diclofenaco potassico','Fenaflan','TEUTO','SUSPENSAO ORAL 15MG/ML');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (7, 'diclofenaco potassico','Fenaren','UNIAO QUIMICA','SUSPENSAO ORAL 15MG/ML');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (8, 'diclofenaco potassico','Neotaflan','BRAINFARMA','SOL. INJETAVEL 25MG/ML');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (9, 'diclofenaco potassico','Probenxil','CIMED','COMP. REV. 50MG');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (10, 'diclofenaco potassico','Probenxil','CIMED','SUSPENSAO ORAL 15MG/ML');
INSERT INTO SC_MEDICAMENTO (ID, NOME_GENERICO, NOME_FABRICA, FABRICANTE, CONCENTRACAO_FORMA_FARMACEUTICA) VALUES (11, 'diclofenaco resinato','Diclac P','SANDOZ','SUSPENSAO ORAL 44,94 MG/ML'); 

-- MEDICOS
DELETE FROM SC_MEDICO;
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values (99,'9999', '41207727130', '1901-01-01', 'NOME', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 1,'0001', '21228022780', '1980-01-01', 'Tomás Leonardo Iago Cardoso', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 2,'0002', '60074180738', '1981-02-02', 'Diogo Oliver Mendes', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 3,'0003', '89984152324', '1982-03-03', 'Joaquim Kaique Igor Pereira', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 4,'0004', '16694260091', '1983-04-04', 'Ruan Iago Alexandre Araújo', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 5,'0005', '29725008731', '1984-05-05', 'Mário Miguel Julio da Rocha', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 6,'0006', '68184554508', '1985-06-06', 'Elza Priscila Liz Peixoto', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 7,'0007', '89828149494', '1986-07-07', 'Andrea Sophie Barros', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 8,'0008', '95274469027', '1987-08-08', 'Kamilly Márcia Santos', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values ( 9,'0009', '52640009800', '1988-09-09', 'Francisca Emanuelly Almada', 'RUA');
INSERT INTO SC_MEDICO  (ID, CRM, CPF, DT_NASCIMENTO, NOME, ENDERECO) values (10,'0010', '61512078158', '1989-10-10', 'Natália Eloá Valentina Ribeiro', 'RUA');
