<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags"%>

<sec:authorize access="hasRole('ROLE_PERFIL_ADMIN')" var="isAdmin"  />
<sec:authorize access="hasRole('ROLE_PERFIL_MEDICO')" var="isMedico" />
<sec:authorize access="hasRole('ROLE_PERFIL_RECEPCIONISTA')" var="isRecepcionista" />

<sec:authorize access="hasRole('ROLE_LISTAR_MEDICO'  )" var="listarMedico"  />
<sec:authorize access="hasRole('ROLE_INCLUIR_MEDICO' )" var="incluirMedico" />
<sec:authorize access="hasRole('ROLE_EDITAR_MEDICO'  )" var="editarMedico" />
<sec:authorize access="hasRole('ROLE_EXCLUIR_MEDICO' )" var="excluirMedico" />

<c:set var="listarMedico"  scope="session" value="${listarMedico}"/>
<c:set var="incluirMedico" scope="session" value="${incluirMedico}"/>
<c:set var="editarMedico"  scope="session" value="${editarMedico}"/>
<c:set var="excluirMedico" scope="session" value="${excluirMedico}"/>
<c:set var="medico" scope="session" value="${listarMedico || incluirMedico || editarMedico || excluirMedico}"/>




<%--
 ROLE_ANTIGO
 ROLE_ATENDER
 ROLE_CRIAR_AGENDA_AGENDAMENTO
 ROLE_DESMARCAR_HORARIO_AJAX_JSON
 ROLE_EDITAR_AGENDAMENTO
 ROLE_EDITAR_ATENDIMENTO
 ROLE_EDITAR_EXAME
 ROLE_EDITAR_GRUPO
 ROLE_EDITAR_MEDICAMENTO
 ROLE_EDITAR_MEDICO
 ROLE_EDITAR_PACIENTE
 ROLE_EDITAR_RECEITA
 ROLE_EDITAR_RECEPCIONISTA
 ROLE_EDITAR_RESULTADOEXAME
 ROLE_EDITAR_SOLICITACAOEXAME
 ROLE_EXCLUIR_AGENDAMENTO
 ROLE_EXCLUIR_ATENDIMENTO
 ROLE_EXCLUIR_EXAME
 ROLE_EXCLUIR_GRUPO
 ROLE_EXCLUIR_MEDICAMENTO
 ROLE_EXCLUIR_MEDICO
 ROLE_EXCLUIR_PACIENTE
 ROLE_EXCLUIR_RECEITA
 ROLE_EXCLUIR_RECEPCIONISTA
 ROLE_EXCLUIR_RESULTADOEXAME
 ROLE_EXCLUIR_SOLICITACAOEXAME
 ROLE_EXIBIR_CALENDARIO_AGENDAMENTO
 ROLE_EXIBIR_CALENDARIO_AGENDAMENTO_MEDICO
 ROLE_EXIBIR_CALENDARIO_VAGAS_AGENDAMENTO
 ROLE_EXIBIR_CALENDARIO_VAGAS_AGENDAMENTO_MEDICO
 ROLE_FULLCALENDAR_LISTAR_HORARIO_OCUPADO_JSON
 ROLE_FULLCALENDAR_LISTAR_HORARIO_VAGO_JSON
 ROLE_INCLUIR_AGENDAFORM
 ROLE_INCLUIR_AGENDAMENTO
 ROLE_INCLUIR_ATENDIMENTO
 ROLE_INCLUIR_CONSULTA_AGENDAMENTO
 ROLE_INCLUIR_EXAME
 ROLE_INCLUIR_GRUPO
 ROLE_INCLUIR_MEDICAMENTO
 ROLE_INCLUIR_MEDICO
 ROLE_INCLUIR_PACIENTE
 ROLE_INCLUIR_RECEITA
 ROLE_INCLUIR_RECEPCIONISTA
 ROLE_INCLUIR_RESULTADOEXAME
 ROLE_INCLUIR_SOLICITACAOEXAME
 ROLE_LISTAR_AGENDAMENTO
 ROLE_LISTAR_ALL_EXAME_JSON
 ROLE_LISTAR_ALL_MEDICO_JSON
 ROLE_LISTAR_ALL_PACIENTE_JSON
 ROLE_LISTAR_ATENDIMENTO
 ROLE_LISTAR_EXAME
 ROLE_LISTAR_EXAME_JSON
 ROLE_LISTAR_GRUPO
 ROLE_LISTAR_HISTORICO_CLINICO_PACIENTE
 ROLE_LISTAR_HISTORICO_CLINICO_PACIENTE_FORM
 ROLE_LISTAR_HORARIO_VAGO_JSON
 ROLE_LISTAR_MEDICAMENTO
 ROLE_LISTAR_MEDICAMENTO_JSON
 ROLE_LISTAR_MEDICO
 ROLE_LISTAR_MEDICO_JSON
 ROLE_LISTAR_PACIENTE
 ROLE_LISTAR_PACIENTE_JSON
 ROLE_LISTAR_RECEITA
 ROLE_LISTAR_RECEPCIONISTA
 ROLE_LISTAR_RESULTADOEXAME
 ROLE_LISTAR_SOLICITACAOEXAME
 ROLE_LOGIN
 ROLE_LOGINERRADO
 ROLE_MARCAR_HORARIO_AJAX_JSON
 ROLE_PERFIL_ADMIN
 ROLE_PERFIL_MEDICO
 ROLE_PESQUISAR_AGENDAMENTO
 ROLE_PRIVADO
 ROLE_PRIVADOAPI
 ROLE_PRIVADOHOME
 ROLE_PRIVADOINICIO
 ROLE_REGISTRATION 
 --%>